config/routes.rb
Rails.application.routes.draw do
 
  root 'memos#index'
  devise_for :users
  
  resources :memos #모든 route 한번에 끝내는 문장!  
  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :memo
  
  validates :content, presence: true, length: {maximum: 50}
end

app/models/memo.rb
class Memo < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    
    validates :title, presence: true, length: {maximum: 50}
    validates :content, presence: true, length: {maximum: 1000}
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!, except: [ :index]
  # Create
  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.new
    @memo.user_id = params[:memo][:user_id]
    @memo.title   = params[:memo][:title]
    @memo.content = params[:memo][:content]
    if @memo.save
      #redirect_to memo_path(@memo)
      redirect_to @memo
    else
      redirect_to :back
    end
  end
# Read
  def show
    @memo = Memo.find(params[:id])
  end

  def index
    @memos = Memo.order(created_at: :DESC).page(params[:page]).per(10)
    
  end

  # Update
  def edit
    @memo = Memo.find(params[:id])
  end

  def update
    @memo = Memo.find(params[:id])
    @memo.user_id = params[:memo][:user_id]
    @memo.title   = params[:memo][:title]
    @memo.content = params[:memo][:content]
    if @memo.save
      #redirect_to memo_path(@memo)
      redirect_to @memo
    else
      redirect_to :back
    end
  end

  # Destroy
  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy!
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
  def icon name
    content_tag('span', '', class: "glyphicon glyphicon-#{name}")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'Memo app', root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <!--<li><a href="/">Home</a></li>-->
        <li><%= link_to 'Home', root_path %></li>
        <%# FIXME New memo path 설정하기 %>
        <li><%= link_to 'New Memo', new_memo_path %></li>
        <%# TODO 로그인/로그아웃 상태에 따라 바꾸기 완성하기 %>
        <% if user_signed_in? %>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Log in', new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <!--<div class="alert alert-<%#= message_type %>"><%#= message %></div>-->  
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  
<%= yield %>


</div>
  
<%= console if Rails.env.development? %>
</body>
</html>

app/views/memos/_form.html.erb
<%= bootstrap_form_for(@memo) do |f| %>  
    <div class="actions">
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.text_field :title %>
        <%= f.text_area :content, label: '내용', class: "tinymce", rows: 15, cols: 120 %>
        <%= tinymce %>
        <%= f.submit %>
    </div>
<% end %>

app/views/memos/edit.html.erb
<h1>글 수정하기</h1>


<%= link_to 'cancel', @memo %>
<hr>
<%= render 'form' %>

app/views/memos/index.html.erb
<h1>Hack Your Memo</h1>

<%= icon 'heart' %><%= link_to('Memo 하러 가기', new_memo_path) if user_signed_in?  %>
  <table class="table table-fit">
    <thead>
    <tr>
      <th>title</th>
      <th>user</th>
      <th>comments</th>
    </tr>
    </thead>
    <tbody>
    <% @memos.each do |memo| %>
        <tr>
          <td><%= link_to memo.title, memo_path(memo) %></td>
          <td><%= memo.user.email %></td>
          <td><%= memo.comments.count %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @memos %>
</div>

app/views/memos/new.html.erb
<h1>새로운 글 쓰기</h1>

<hr>
<%= render 'form' %>

app/views/memos/show.html.erb
<h1><%= @memo.id %>번 글 보기</h1>


<h1>제목: [<%= @memo.title %>]</h1>
<hr>
<h4>by <a href="mailto:<%= @memo.user.email %>"><%= @memo.user.email %></a> </h4>
<h5><p><%= icon 'time' %><%= local_time @memo.created_at %></p></h5>
<% if current_user == @memo.user %>
    <%= icon 'pencil' %><%= link_to '수정하기', edit_memo_path %> | <%= icon 'trash' %><%= link_to '삭제하기', memo_path, method: :delete %>
<% end %>

<hr>
<%= @memo.content.html_safe %>
<hr>